#!/usr/bin/env bash

########################################################
###                        Help                      ###
########################################################

HELP='
Application process actions.

Usage:

    application [action]

Parameters:

    * action

        Application process action.

        - start              Start the application.
        - restart            Restart the application.
        - startOrRestart     Start or restart the application.
        - stop               Stop the application.
'

########################################################
###                     Variables                    ###
########################################################

# Project name
if [[ -z $PROJECT_NAME ]]; then
    echo 'Error: Set the "PROJECT_NAME" variable'
    exit 1
fi

# Node environment
if [[ -z $NODE_ENV ]]; then
    NODE_ENV='development'
fi

# Node
NODE='node'

# Process manager
PROCESS_MANAGER='pm2'

########################################################
###                      Export                      ###
########################################################

# Node config directory
export NODE_CONFIG_DIR="$PWD/configs/node"

########################################################
###                      Helpers                     ###
########################################################

#
# Print a title of action
#
# @1 {string} Title
#
printTitle() {
    echo "===> $1"
}

#
# Print info until start application
#
printInfoBeforeStart() {
    echo "User:            $(whoami)"
    echo "Environment:     $NODE_ENV"
    echo "Nodejs version:  $("$NODE" --version)"
}

#
# Check if the application is running
#
isAppRunning() {
    "$PROCESS_MANAGER" id "$PROJECT_NAME" | tail -1 | grep -E '[0-9]+' > /dev/null
}

########################################################
###                     Actions                      ###
########################################################

#
# Help
#
help() {
    echo "$HELP"
}

#
# Start the application
#
start() {
    printTitle 'Running the application'

    if isAppRunning; then
        echo '[warn] Application already started'
    else
        printInfoBeforeStart

        "$PROCESS_MANAGER" start index.js \
            -n "$PROJECT_NAME" \
            --no-autorestart \
            --log-date-format='YYYY-MM-DD HH:mm:ss.SSS'
    fi
}

#
# Restart the application
#
restart() {
    printTitle 'Restarting the application'

    if isAppRunning; then
        printInfoBeforeStart

        "$PROCESS_MANAGER" restart "$PROJECT_NAME" --update-env
    else
        echo "[warn] Application isn't running"
    fi
}

#
# Stop and start the application
#
stopAndStart() {
    stop
    start
}

#
# Start or restart the application
#
startOrRestart() {

    if isAppRunning; then
        restart
    else
        start
    fi
}

#
# Stop the application
#
stop() {
    printTitle 'Stopping the application'

    if isAppRunning; then
        "$PROCESS_MANAGER" delete "$PROJECT_NAME"
    else
        echo '[warn] Application already stopped'
    fi
}

########################################################
###                    Call action                   ###
########################################################

case "$1" in
    start|restart|stopAndStart|startOrRestart|stop)
        "$1"
    ;;
    *)
        help
    ;;
esac
