#!/usr/bin/env bash

########################################################
###                        Help                      ###
########################################################

HELP='
Debug.

Usage:

    debug action

Parameters:

    * action

        Debug action.

        - process     Show the application process.
        - logs        Show application logs.
'

########################################################
###                     Variables                    ###
########################################################

# Project name
if [[ -z $PROJECT_NAME ]]; then
    echo 'Error: Set the "PROJECT_NAME" variable'
    exit 1
fi

# Process manager
PROCESS_MANAGER='pm2'

########################################################
###                      Helpers                     ###
########################################################

#
# Print a title of action
#
# @1 {string} Title
#
printTitle() {
    echo "===> $1"
}

########################################################
###                     Actions                      ###
########################################################

#
# Help
#
help() {
    echo "$HELP"
}

#
# Show the current process
#
process() {
    printTitle 'Application process'

    "$PROCESS_MANAGER" show "$PROJECT_NAME"
}

#
# Show logs
#
logs() {
    printTitle 'Application logs'

    "$PROCESS_MANAGER" logs "$PROJECT_NAME" --timestamp 'YYYY-MM-DD HH:mm:ss.ms'
}


########################################################
###                    Call action                   ###
########################################################

case "$1" in
    process|logs)
        "$1"
    ;;
    *)
        help
    ;;
esac
